- name: copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb client
  ansible.builtin.shell: dnf install mongodb-org-shell -y

- name: get the entries count
  ansible.builtin.command: mongo --host mongodb.learndevops.space --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: entries_count
  when: component == "catalogue"

- name: get the entries count
  ansible.builtin.command: mongo --host mongodb.learndevops.space --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: entries_count
  when: component == "user"

- name: Print the count
  ansible.builtin.debug:
    msg: "entries count is: {{entries_count}}"

- name: load catalogue data into mongodb
  ansible.builtin.command: mongo --host mongodb.learndevops.space < /app/schema/catalogue.js
  when: entries_count.stdout == "0"

- name: enable and start catalogue
  ansible.builtin.service:
    name: catalogue
    enabled: yes 
    state: restarted